### ISSUE TITLE
P749 : Testing the customer form component.

### ISSUE THREAD

**Issue by targettadams** [markjprice/cs11dotnet7#31]
When creating a new customer, there appears to be an intermittent concurrency issue related to the OnValidSubmit callback ('Create' in this case): 

```
await service.CreateCustomerAsync(customer);
navigation.NavigateTo("customers");
```
And then, upon navigation, we are doing (in Customers.razor):

```
 protected override async Task OnParametersSetAsync()
 {
     if (string.IsNullOrWhiteSpace(Country))
     {
         customers = await service.GetCustomersAsync();
     }
     else
     {
         customers = await service.GetCustomersAsync(Country);
     }
 }
```

Despite awaiting each async call, there is an intermittent InvalidOperationException being thrown:

```
System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Northwind.BlazorServer.Pages.Customers.OnParametersSetAsync() in C:\Users\chris\source\repos\PracticalApps\Northwind.BlazorServer\Pages\Customers.razor:line 61
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```

I'm pretty certain the code has been copied properly.

**Comment by markjprice** [comment]
Thank you for raising this issue. I have added an errata item for it:
https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/errata.md#page-724---getting-entities-into-a-component
